export interface HookBeforeCreate { beforeCreate(): void; }
export interface HookCreated { created(): void; }
export interface HookBeforeMount { beforeMount(): void; }
export interface HookMounted { mounted(): void; }
export interface HookBeforeUpdate { beforeUpdate(): void; }
export interface HookUpdated { updated(): void; }
export interface HookActivated { activated(): void; }
export interface HookDeactivated { deactivated(): void; }
export interface HookBeforeDestroy { beforeDestroy(): void; }
export interface HookBeforeUnmount { beforeUnmount(): void; }
export interface HookDestroyed { destroyed(): void; }
export interface HookUnmounted { unmounted(): void; }
export interface HookRenderTracked { renderTracked(): void; }
export interface HookRenderTriggered { renderTriggered(): void; }
export interface HookErrorCaptured { errorCaptured(): void; }
export interface HookServerPrefetch { serverPrefetch(): void; }
export interface HookRender { render(): void; }
