export { Component, ComponentBase } from './component'
export { decorator as Setup } from './option/setup'
export { decorator as Ref } from './option/ref'
export { decorator as Watch } from './option/watch'
export { decorator as Prop } from './option/props'
export { decorator as Provide } from './option/provide'
export { decorator as Inject } from './option/inject'
export { decorator as Emit } from './option/emit'
export { decorator as VModel, decorator as Model } from './option/vmodel'
export { decorator as Vanilla } from './option/vanilla'
export { decorator as Hook } from './option/methodsAndHooks'
export { createDecorator } from './custom/custom'
export { mixins } from './mixins'
export { TSX } from './tsx/type'
import { Base } from './class'
export { Base }
export const Vue = Base
export { toNative } from './component'
